name: Batfish CICD Demo - PR

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      - name: Generate configuration
        run: |
          echo 1.Download batfish container
          docker pull batfish/allinone
          echo
          echo 2.Run batfish service
          docker run -p 8888:8888 batfish/allinone
          echo
          echo Is it running?
          docker container ls -a
          echo

  pre-tests:
    name: "Pre-tests"
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
            python-version: 3.8
      - uses: syphar/restore-pip-download-cache@v1
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Recheck container is up
        run: |
             docker container ls -a
             echo
             docker run -p 8888:8888 batfish/allinone
             echo
      - name: Perform Batfish pre-tests
        run: |
            pytest -vvv . --disable-pytest-warnings
